services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=https://api-pos.masivaguna.com/api


