services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
        environment:
            - API_BASE_URL=http://localhost:8081/api
